export const USER_CREATED_SUCCESSFULLY="USER_CREATED_SUCCESSFULLY";
export const USER_CREATION_FAILED = "USER_CREATION_FAILED";
export const USER_LOGEDIN="USER_LOGEDIN";
export const USER_LOGEDIN_FAILED = "USER_LOGEDIN_FAILED";
